// src/app/shared/components/list-activities/activity/activity.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { IActivityModel } from 'src/app/models/activity';

@Component({
  selector: 'app-activity',
  templateUrl: './activity.component.html',
  styleUrls: ['./activity.component.scss'],
})
export class ActivityComponent implements OnInit {
  @Input() activity: IActivityModel = {};

  public boolTabOpen = true;
  public ctnVignettes;

  constructor() {
    this.ctnVignettes = document.getElementsByClassName('ctn-vignette');
  }

  ngOnInit() {}

  onResize() {}

  calcHeight(): string {
    return `${this.ctnVignettes[0].clientWidth / 2}px`;
  }

  classVignette() {
    return `vignette tab-open ${this.activity.url}`;
  }
  isEntex() {
    return this.activity.title === 'Entex' ? true : false;
  }
  isFitness() {
    return this.activity.title === 'Fitness' ? true : false;
  }
  isCombat() {
    return this.activity.title === 'Combat' ? true : false;
  }
  isSportCo() {
    return this.activity.title === 'Sports collectifs' ? true : false;
  }
  isRaquette() {
    return this.activity.title === 'Sports Raquettes' ? true : false;
  }
  isOutdoor() {
    return this.activity.title === 'Sports plein air' ? true : false;
  }

  openTab() {
    if (this.boolTabOpen) {
      this.boolTabOpen = false;
    } else {
      this.boolTabOpen = true;
    }
  }
}

<div class="ctn-vignette">
  <div class="vignette-text-title">
    <div class="activity-logo">
      <app-svg-fitness *ngIf="isFitness()" />
      <app-svg-fitness *ngIf="isEntex()" />
      <app-svg-combat *ngIf="isCombat()" />
      <app-svg-sport-co *ngIf="isSportCo()" />
      <app-svg-raquettes *ngIf="isRaquette()" />
      <app-svg-outdoor *ngIf="isOutdoor()" />
    </div>
    <h5>{{activity.title}}</h5>
  </div>
  <!-- <transition name="slide"> -->
  <div [class]="classVignette()" [style.height]="calcHeight()">
    <div class="vignette-text">
      <div class="txt-sports">
        <div *ngFor="let sport of activity.sports">
          <p class="small">{{sport.name}}</p>
        </div>
      </div>
    </div>
  </div>
  <!-- </transition> -->
</div>

// src/components/section-sport-en-entreprise/activitees/activity/activity.vue
<template lang="html" src="./activity.html"></template>

<script>

export default {
  components: {

  },
  props: ['activity'],
  data() {
    return {
      boolTabOpen: true,
      classTabOpen: 'tab-open'
    }
  },
  computed: {
    isTabOpen() {
      return this.boolTabOpen? this.classTabOpen : ''
    },
    isFitness() {
      return this.activity.title == "Fitness" ? true : false
    },
    isCombat() {
      return this.activity.title == "Combat" ? true : false
    },
    isSportCo() {
      return this.activity.title == "Sports collectifs" ? true : false
    },
    isRaquette() {
      return this.activity.title == "Sports Raquettes" ? true : false
    },
    isOutdoor() {
      return this.activity.title == "Sports plein air" ? true : false
    },
  },
  methods: {
    openTab(){
      if (this.boolTabOpen){
        this.boolTabOpen = false
      } else {
        this.boolTabOpen = true
      }
    }
  }
}
</script>

<style lang="scss" src="./activity.scss"></style>
